dist: xenial
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

  # pipenv has issues with pypy
  #- "pypy"
  #- "pypy3"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install --upgrade pip pipenv
  - pip --version
  - pipenv --version
  - pip freeze
  - make setup
  - pipenv run pip freeze

script:
  - make ci

