build: "off"

environment:
  PIP_USE_PEP517: "no"
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

install:
  - pip --version
  - pip install pipenv
  - pipenv --support
  - pip freeze
  - pipenv install --dev --skip-lock
  - pipenv run pip freeze

test_script:
  - pipenv run py.test

